{
 "title": "Apache Error Dashboard",
 "tags": [ "Log" ],
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Severity Breakdown",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT ts,        sum(notice_count) AS notice,        sum(warn_count) AS warn,        sum(error_count) AS error,        sum(crit_count) AS crit,        sum(alert_count) AS alert,        sum(emerg_count) AS emerg FROM logs_db.apache_error_levels_per_minute GROUP BY ts ORDER BY ts; "
    }
   ]
  },
  {
   "title": "Error Volume Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT ts, sum(error_count) AS error_count FROM logs_db.apache_errors_per_minute GROUP BY ts ORDER BY ts; "
    }
   ]
  },
  {
   "title": "Errors by Module",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT module, count(*) AS hits FROM logs_db.apache_error_logs GROUP BY module ORDER BY hits DESC LIMIT 5; "
    }
   ]
  },
  {
   "title": "Process / Thread Analysis (pid/tid)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT pid, count(*) AS hits FROM logs_db.apache_error_logs GROUP BY pid ORDER BY hits DESC LIMIT 10; "
    }
   ]
  },
  {
   "title": "Security Indicators (Attacks / Scans)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT * FROM logs_db.apache_error_logs WHERE error_message ILIKE '%ssl%' ORDER BY timestamp DESC LIMIT 10; "
    }
   ]
  }
 ]
}