{
 "title": "Apache Combined Dashboard",
 "tags": [ "Log" ],
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  { "title": "Traffic Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status Codes Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT     ts,     sumIf(hits, status BETWEEN 200 AND 299) AS s2xx,     sumIf(hits, status BETWEEN 300 AND 399) AS s3xx,     sumIf(hits, status BETWEEN 400 AND 499) AS s4xx,     sumIf(hits, status BETWEEN 500 AND 599) AS s5xx FROM logs_db.apache_status_per_minute GROUP BY ts ORDER BY ts; "
    }
   ]
  },
  {
   "title": "Requests Over Time ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT ts, sum(hits) FROM logs_db.apache_hits_per_minute GROUP BY ts ORDER BY ts; "
    }
   ]
  },
  { "title": "Client Behavior", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Traffic by HTTP Method",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT method, count(*) AS hits FROM logs_db.apache_access_logs GROUP BY method ORDER BY hits DESC; "
    }
   ]
  },
  { "title": "Performance Monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Avg & p95 Response Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "rawSql": "SELECT     ts,     avgMerge(avg_state) AS avg_size,     quantileMerge(0.95)(p95_state) AS p95_size FROM logs_db.apache_response_size_per_minute GROUP BY ts ORDER BY ts; "
    }
   ]
  },
  {
   "title": "Top Slowest Endpoints",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "rawSql": "SELECT     path,     avg(size) AS avg_response_size FROM logs_db.apache_access_logs GROUP BY path ORDER BY avg_response_size DESC LIMIT 5; "
    }
   ]
  },
  { "title": "Path / API Usage Analytics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Top Requested Paths",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "rawSql": "SELECT path, count(*) AS hits FROM logs_db.apache_access_logs GROUP BY path ORDER BY hits DESC LIMIT 15; "
    }
   ]
  }
 ]
}