{
 "title": "Clickhouse",
 "description": "Clickhouse metrics",
 "tags": [
  "clickhouse",
  "db"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Query",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(clickhouse_query_total[1m])"
    }
   ]
  },
  {
   "title": "Merge",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "clickhouse_merge", "legendFormat": "merge {{job}}" },
    {
     "expr": "rate(clickhouse_merged_rows_total[1m])",
     "legendFormat": "rate {{job}}"
    }
   ]
  },
  {
   "title": "MergeTree Data Parts",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 1, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(clickhouse_table_parts_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Delayed inserts",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 6, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(clickhouse_delayed_inserts)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total query ",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 11, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "clickhouse_query_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Compressed Read Buffer",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(clickhouse_compressed_read_buffer_bytes_total[1m])",
     "legendFormat": "{{job}}"
    },
    {}
   ]
  },
  {
   "title": "Read/Write",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "clickhouse_read" },
    { "expr": "clickhouse_write" }
   ]
  },
  {
   "title": "Pool Tasks",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "clickhouse_background_pool_task",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "clickhouse_tcp_connection", "legendFormat": "tcp {{instance}}" },
    { "expr": "clickhouse_http_connection", "legendFormat": "http {{instance}}" },
    {
     "expr": "clickhouse_interserver_connection",
     "legendFormat": "interserver"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "clickhouse_memory_tracking" }
   ]
  },
  {
   "title": "Cache rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(clickhouse_mark_cache_misses_total[5m])",
     "legendFormat": "misses {{job}}"
    },
    {
     "expr": "rate(clickhouse_mark_cache_hits_total[5m])",
     "legendFormat": "hits {{job}}"
    }
   ]
  }
 ]
}