{
 "title": "Combined Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  { "title": "Stat Panel", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Global Volume (Stat Panel)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*) FROM logs_db.unified_logs_view;"
    }
   ]
  },
  {
   "title": "Error Rate (Stat Panel)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT    (countIf(        match(level_or_status, '4\\d\\d|5\\d\\d|Error|Critical|Alert|Emergency')    ) / count()) * 100 FROM logs_db.unified_logs_view WHERE timestamp >= $__fromTime AND timestamp <= $__toTime"
    }
   ]
  },
  {
   "title": "Source Distribution",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT container_name, count() FROM logs_db.unified_logs_view WHERE timestamp >= $__fromTime AND timestamp <= $__toTime GROUP BY container_name"
    }
   ]
  },
  {
   "title": "Timeline",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Log Volume Over Time",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
     "targets": [
      {
       "rawSql": "SELECT     toStartOfMinute(timestamp) as time,     count() as log_count FROM logs_db.unified_logs_view GROUP BY time ORDER BY time ASC;"
      }
     ]
    },
    {
     "title": "Total Bandwidth/Bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
     "targets": [
      {
       "rawSql": "SELECT     toStartOfMinute(timestamp) as time,     sum(size_bytes) as total_bytes FROM logs_db.unified_logs_view WHERE log_type IN ('JSON Service', 'Apache Access')   AND timestamp >= $__fromTime AND timestamp <= $__toTime GROUP BY time ORDER BY time"
      }
     ]
    }
   ]
  },
  { "title": "HTTP Traffic Analysis", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "HTTP Status Codes",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT     level_or_status as status_code,     count() as count FROM logs_db.unified_logs_view WHERE log_type IN ('JSON Service', 'Apache Access')   AND timestamp >= $__fromTime AND timestamp <= $__toTime GROUP BY status_code ORDER BY count DESC"
    }
   ]
  }
 ]
}