{
 "title": "Json Dashboard",
 "tags": [ "Log" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Traffic Over Time (Requests per Minute)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT     minute,     requests FROM logs_db.json_1min_agg ORDER BY minute; "
    }
   ]
  },
  {
   "title": "Response Size Trend (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT     minute,     bytes_avg FROM logs_db.json_1min_agg ORDER BY minute; "
    }
   ]
  },
  {
   "title": "Top Requested Endpoints (Top PATHS)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT    request,   count(*) AS hits FROM logs_db.json_service_logs GROUP BY request ORDER BY hits DESC LIMIT 10; "
    }
   ]
  },
  {
   "title": "Requests by HTTP Method",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT    method,   count(*) AS total FROM logs_db.json_service_logs GROUP BY method ORDER BY total DESC; "
    }
   ]
  },
  {
   "title": "Combined Summary Panel",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT     count(*) AS total_logs,     countIf(status >= 500) AS server_errors,     countIf(status >= 400 AND status < 500) AS client_errors,     countIf(status BETWEEN 200 AND 299) AS successful,     uniqExact(host) AS unique_hosts FROM logs_db.json_service_logs; "
    }
   ]
  },
  {
   "title": "HTTP Status Code Breakdown",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT    status,   count(*) AS total FROM logs_db.json_service_logs GROUP BY status ORDER BY status; "
    }
   ]
  },
  {
   "title": "Table of Recent Logs (Live View)",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT    timestamp,   method,   status,   request,   host,   referer FROM logs_db.json_service_logs ORDER BY timestamp DESC LIMIT 20; "
    }
   ]
  }
 ]
}