{
 "title": "Syslog Dashboard",
 "tags": [ "Log" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Overall Syslog Volume Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT ts, sum(log_count) AS log_count FROM logs_db.syslogs_per_minute GROUP BY ts ORDER BY ts; "
    }
   ]
  },
  {
   "title": "Severity Trends Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT ts,        sum(debug_count) AS debug,        sum(info_count) AS info,        sum(notice_count) AS notice,        sum(warn_count) AS warn,        sum(err_count) AS err,        sum(crit_count) AS crit,        sum(alert_count) AS alert,        sum(emerg_count) AS emerg FROM logs_db.syslogs_severity_per_minute GROUP BY ts ORDER BY ts; "
    }
   ]
  },
  {
   "title": "ProcID Analysis",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT procid, count(*) AS hits FROM logs_db.rfc3164_syslogs GROUP BY procid ORDER BY hits DESC LIMIT 10; "
    }
   ]
  },
  {
   "title": "Facility Analysis",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT facility, count(*) AS hits FROM logs_db.rfc3164_syslogs GROUP BY facility ORDER BY hits DESC LIMIT 10; "
    }
   ]
  },
  {
   "title": "Errors / Alerts Monitoring",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT * FROM logs_db.rfc3164_syslogs WHERE severity IN ('err','crit','alert','emerg') ORDER BY timestamp DESC LIMIT 50; "
    }
   ]
  }
 ]
}